name: Clojure CI - Linter

on: [ push ]

jobs:
  linter-check:
    name: Linter Check
    runs-on: ubuntu-22.04

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: lein deps
      - name: Linter Check
        run: lein lint
